### ISSUE TITLE
markovchain package compilation issue

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#156] opened 2018-12-23 12:13 UTC
Currently, it is impossible to compile markovchain package. It breaks before checking. Probably a routine registration issue:

`Updating markovchain documentation
Updating roxygen version in Z:\markovchain/DESCRIPTION
Loading markovchain
in method for 'coerce' with signature '"msm","markovchain"': no definition for class "msm"
in method for 'coerce' with signature '"msm.est","markovchain"': no definition for class "msm.est"
in method for 'coerce' with signature '"etm","markovchain"': no definition for class "etm"
in method for 'coerce' with signature '"markovchain","igraph"': no definition for class "igraph"
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a "DLLInfo" object. See getLoadedDLLs()
Calls: <Anonymous> ... assignNativeRoutines -> getDLLRegisteredRoutines.DLLInfo`

The issue is breaking.

**Comment by ncordon** [comment] 2018-12-26 02:16
Hi Giorgio, I've addressed problems in compilation in Travis CI in 1af19f1. Problem with Travis CI was that [devtools](https://github.com/r-lib/devtools) dev version build was failing, so I have removed the dev version for that package in the configuration for travis.

I cannot reproduce your issue locally. Everything seems to be working fine with R 3.5.2 and R devel (which is the one installed in Travis). Could you please double check this to see if we can close this issue?

**Comment by spedygiorgio** [comment] 2018-12-26 13:51
Dear @ncordon, I seem to be an issue due to roxygen2 recent releases. See [https://stackoverflow.com/questions/53642735/namespace-option-created-by-rcpparmadillo-package-skeleton-causes-error](SO 1) and [https://stackoverflow.com/questions/53642735/namespace-option-created-by-rcpparmadillo-package-skeleton-causes-error/53643187#53643187](SO 2). Changing `useDynLib(markovchain, .registration=TRUE)` to `useDynLib(markovchain)` solved the issue.

**Closed** 2018-12-26 13:52 UTC
Labels: bug

**Comment by ChristelSwift** [comment] 2019-07-23 14:33
I seem to be having that compliation problem too since upgrading to the latest R version 3.6.1.  I tried installing both from CRAN and from github but i'm getting lots of "arma_deprecated" errors:

```
sampler.cpp:107:27: warning: 'sort_index<arma::Mat<double> >' is deprecated [-Wdeprecated-declarations]
  arma::uvec perm = arma::sort_index(prob, 1); //descending sort of index
                          ^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/fn_sort_index.hpp:40:1: note: 'sort_index<arma::Mat<double> >' has been explicitly marked deprecated here
arma_deprecated
^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
sampler.cpp:108:16: warning: 'sort<arma::Col<double> >' is deprecated [-Wdeprecated-declarations]
  prob = arma::sort(prob, 1);  // descending sort of prob
               ^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/fn_sort.hpp:66:1: note: 'sort<arma::Col<double> >' has been explicitly marked deprecated here
arma_deprecated
^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
sampler.cpp:169:27: warning: 'sort_index<arma::Mat<double> >' is deprecated [-Wdeprecated-declarations]
  arma::uvec perm = arma::sort_index(prob, 1); //descending sort of index
                          ^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/fn_sort_index.hpp:40:1: note: 'sort_index<arma::Mat<double> >' has been explicitly marked deprecated here
arma_deprecated
^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
sampler.cpp:170:16: warning: 'sort<arma::Col<double> >' is deprecated [-Wdeprecated-declarations]
  prob = arma::sort(prob, 1);  // descending sort of prob
               ^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/fn_sort.hpp:66:1: note: 'sort<arma::Col<double> >' has been explicitly marked deprecated here
arma_deprecated
^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
4 warnings generated.
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o markovchain.so RcppExports.o classesAndMethods.o ctmcClassesAndMethodsSAI.o ctmcFittingsFunctions.o ctmcProbabilistic.o fitHigherOrder.o fittingFunctions.o multinomCI.o probabilistic.o sampler.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [markovchain.so] Error 1
ERROR: compilation failed for package ‘markovchain’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/markovchain’
Warning in install.packages :
  installation of package ‘markovchain’ had non-zero exit status
```

**Comment by ncordon** [comment] 2019-07-24 14:44
> I seem to be having that compliation problem too since upgrading to the latest R version 3.6.1. I tried installing both from CRAN and from github but i'm getting lots of "arma_deprecated" errors:
> 
> ```
> sampler.cpp:107:27: warning: 'sort_index<arma::Mat<double> >' is deprecated [-Wdeprecated-declarations]
>   arma::uvec perm = arma::sort_index(prob, 1); //descending sort of index
>                           ^
> /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/fn_sort_index.hpp:40:1: note: 'sort_index<arma::Mat<double> >' has been explicitly marked deprecated here
> arma_deprecated
> ^
> /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
>     #define arma_deprecated __attribute__((__deprecated__))
>                                            ^
> sampler.cpp:108:16: warning: 'sort<arma::Col<double> >' is deprecated [-Wdeprecated-declarations]
>   prob = arma::sort(prob, 1);  // descending sort of prob
>                ^
> /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/fn_sort.hpp:66:1: note: 'sort<arma::Col<double> >' has been explicitly marked deprecated here
> arma_deprecated
> ^
> /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
>     #define arma_deprecated __attribute__((__deprecated__))
>                                            ^
> sampler.cpp:169:27: warning: 'sort_index<arma::Mat<double> >' is deprecated [-Wdeprecated-declarations]
>   arma::uvec perm = arma::sort_index(prob, 1); //descending sort of index
>                           ^
> /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/fn_sort_index.hpp:40:1: note: 'sort_index<arma::Mat<double> >' has been explicitly marked deprecated here
> arma_deprecated
> ^
> /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
>     #define arma_deprecated __attribute__((__deprecated__))
>                                            ^
> sampler.cpp:170:16: warning: 'sort<arma::Col<double> >' is deprecated [-Wdeprecated-declarations]
>   prob = arma::sort(prob, 1);  // descending sort of prob
>                ^
> /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/fn_sort.hpp:66:1: note: 'sort<arma::Col<double> >' has been explicitly marked deprecated here
> arma_deprecated
> ^
> /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
>     #define arma_deprecated __attribute__((__deprecated__))
>                                            ^
> 4 warnings generated.
> clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o markovchain.so RcppExports.o classesAndMethods.o ctmcClassesAndMethodsSAI.o ctmcFittingsFunctions.o ctmcProbabilistic.o fitHigherOrder.o fittingFunctions.o multinomCI.o probabilistic.o sampler.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
> ld: library not found for -lgfortran
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [markovchain.so] Error 1
> ERROR: compilation failed for package ‘markovchain’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/markovchain’
> Warning in install.packages :
>   installation of package ‘markovchain’ had non-zero exit status
> ```

Please @ChristelSwift can you open a separate issue for this? I do not think both compilation errors are related, and the one this issue started with was in fact solved
